export const EXAMPLE_QUERIES = [
  "What kinds of topics does {account} post about?",
  "Based on these tweets, what Enneagram type is {account}? If you're unsure, list multiple options.",
  "Based on these tweets, what MBTI is {account}? If you're unsure, list multiple options.",
  "How does {account} seem to perceive themselves based on their tweets?",
  "What kind of person might someone imagine {account} to be if they only read their tweets?",
  "What adjectives best capture {account}’s online personality?",
  "What consistent themes or archetypes does {account} embody (e.g., thinker, rebel, nurturer)?",
  "How authentic does {account} appear to be — do their tweets feel curated or spontaneous?",
  "What kind of reputation might {account} have built unconsciously over time?",
  "If {account}’s tweets were a mirror, what self-image would they reflect?",
  "What emotions does {account} express most often — and which do they seem to avoid?",
  "What topics or events tend to trigger strong emotional reactions in {account}?",
  "Does {account} seem to seek connection, validation, or expression through tweeting?",
  "How does {account}’s emotional tone shift over months or years?",
  "When does {account} sound most alive, passionate, or inspired?",
  "What might {account}’s tweets reveal about their coping mechanisms or stress responses?",
  "Is there evidence of emotional growth or healing in {account}’s timeline?",
  "What appears to drive {account} to tweet — attention, reflection, humor, advocacy, curiosity?",
  "What needs (belonging, recognition, control, freedom, etc.) are most visible in {account}’s writing?",
  "What might {account} be searching for or trying to prove through their online presence?",
  "What topics make {account} feel most purposeful or fulfilled?",
  "What ambitions or longings surface between the lines of {account}’s tweets?",
  "What does {account} seem to believe about people, society, or themselves?",
  "What moral or philosophical positions does {account} return to repeatedly?",
  "Does {account} come across as idealistic, skeptical, pragmatic, or ironic?",
  "How does {account} express disagreement or conviction — gently, humorously, or forcefully?",
  "What implicit assumptions or worldviews shape {account}’s language?",
  "How do {account}’s values seem to evolve over time?",
  "How has {account} changed as a person since they began tweeting?",
  "What were the main “eras” or turning points in {account}’s Twitter life?",
  "Which events or ideas appear to have shifted {account}’s perspective most?",
  "Does {account} show increasing maturity, self-awareness, or openness over time?",
  "What parts of {account} have remained consistent despite the years?",
  "What contradictions exist between what {account} says and how they act?",
  "What fears or insecurities show up indirectly in {account}’s tweets?",
  "Are there emotional tones {account} avoids expressing publicly?",
  "What does {account} criticize in others that they might also wrestle with themselves?",
  "What biases, assumptions, or defensiveness patterns does {account} reveal?",
  "What kind of inner narrator does {account} sound like — critic, philosopher, comedian, dreamer?",
  "How does {account}’s tone toward themselves differ from their tone toward others?",
  "What metaphors or storylines does {account} unconsciously use to describe life?",
  "If {account}’s tweets were chapters of a memoir, what would the chapters be called?",
  "What’s the “thesis statement” of {account}’s Twitter presence — the message beneath everything?",
  "Which corner of the internet would claim {account} as one of their own?",
];

export const FEATURED_QUERIES = [
  "What kinds of topics does {account} post about?",
  "Based on these tweets, what Enneagram and MBTI types are {account}? You may list multiple options.",
  "What were the main eras or turning points in {account}'s life?",
  "What are {account}'s two best tweets? And which one is {account}'s worst?",
];
