export const EXAMPLE_QUERIES = [
  "What kinds of topics does {account} post about?",
  "Based on these tweets, what Enneagram type is {account}? If you're unsure, list multiple options.",
  "Based on these tweets, what MBTI is {account}? If you're unsure, list multiple options.",
  "How do I seem to see myself based on my tweets?",
  "What kind of person would someone imagine me to be if they only read my tweets?",
  "What adjectives best describe my online personality?",
  "What are the consistent themes or archetypes I embody (e.g., thinker, rebel, nurturer)?",
  "How authentic do I seem to be in my tweets — do I sound curated or spontaneous?",
  "What kind of reputation might I have built unconsciously over time?",
  "If my tweets were a mirror, what kind of self-image would they reflect?",
  "What emotions do I express most often — and which do I avoid?",
  "What topics or events tend to trigger strong emotional reactions?",
  "Do I tend to seek connection, validation, or expression through tweeting?",
  "How does my emotional tone change over months or years?",
  "When do I sound most alive, passionate, or inspired?",
  "What might my tweets reveal about my coping mechanisms or stress responses?",
  "Is there evidence of emotional growth or healing in my timeline?",
  "What seems to drive me to tweet — attention, reflection, humor, advocacy, curiosity?",
  "What needs (belonging, recognition, control, freedom, etc.) are most visible in my writing?",
  "What am I searching for or trying to prove through my online presence?",
  "What topics make me feel most purposeful or fulfilled?",
  "What ambitions or longings show up between the lines of my tweets?",
  "What do I appear to believe about people, society, or myself?",
  "What moral or philosophical positions do I return to again and again?",
  "Do I come across as idealistic, skeptical, pragmatic, or ironic?",
  "How do I express disagreement or conviction — gently, humorously, or forcefully?",
  "What implicit assumptions or worldviews shape my language?",
  "How do my values seem to evolve over time?",
  "How have I changed as a person since I started tweeting?",
  "What were the main “eras” or turning points in my Twitter life?",
  "Which events or ideas seem to have shifted my perspective most?",
  "Do I show increasing maturity, self-awareness, or openness over time?",
  "What parts of me have stayed consistent despite the years?",
  "What contradictions exist between what I say and how I act?",
  "What fears or insecurities show up indirectly in my tweets?",
  "Are there emotional tones I avoid expressing publicly?",
  "What do I criticize in others that I might also wrestle with myself?",
  "What biases, assumptions, or defensiveness patterns do I reveal?",
  "What kind of inner narrator do I sound like — critic, philosopher, comedian, dreamer?",
  "How does my tone toward myself differ from my tone toward others?",
  "What metaphors or storylines do I unconsciously use to describe life?",
  "If my tweets were chapters of a memoir, what would the chapters be called?",
  "What’s the “thesis statement” of my Twitter presence — the message beneath everything?",
  "Which corner of the internet would claim me as one of their own?",
];

export const FEATURED_QUERIES = [
  "What kinds of topics does {account} post about?",
  "Based on these tweets, what Enneagram and MBTI types are {account}? You may list multiple options.",
  "What seems to motivate {account} to tweet, e.g. attention, reflection, humor, advocacy, curiosity?",
  "What were the main eras or turning points in {account}'s Twitter life?",
];
